---
title: "Knitting"
author: "Paul V"
date: "11/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries and working directory
```{r, results='hide', warning=FALSE, message = FALSE}

library(psych)
library(ggridges)
library(kableExtra)
library(mgsub)
library(vroom)
library(stringr)
library(ggeasy)
library(gridExtra)
library(brms)
library(lme4)
library(sjPlot)
library(CCA)
library(ordPens)
library(kableExtra)
library(MASS)
library(bayesplot)
library(rstanarm)
library(tidyverse)

#Set working directory
setwd("E:/R stuff/knitting") #for home PC
#setwd("/home/vanagpau/R/knitting") #for laptop


#setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
```


## Data import and wrangling
```{r, warning=FALSE, message = FALSE}

# Import data set of 7000+ participants into data frame.
df <- read_csv(file = "Kntiing7000dat1.csv")

# Removal of unnecessary columns
df <- df[,-c(2,23,24)]

# Changing column names
df <- df %>%  rename(Participant = "Unique Response Number",
         Gender = "71. What is your gender?",
         BDI = "BDI (0-9-16-29-63)",
         FMI = "FMI (14-56)",
         PSS = "PSS (0-13-26-40)",
         STAI = "STAI (20-80)",
         #country of birth
         Cofbirth = "72. In which country were you born?" ,
         #Current country
         Ccountry = "73. In which country do you currently live? Which region?",
         #Date of Birth
         DOB = "74. What is the year of your birth?"  ,
         #frequency of kniiting
         Freq_knit = "76. About knitting..." ,
         #length of knitting sessions
         Session_L_Knit = "77. How long does a typical knitting session last?"   ,
         #when learn to knit
         learn_knit = "78. When did you learn to knit?" ,
         how_long_knit = "79. How long have you been knitting regularly?" ,
         CrochetQ = "80. About crochet..." ,
         Session_L_Croch = "81. How long does a typical crochet session last?" ,
         Age_beg_Croch = "82. At what age did you learn to crochet?",
         #How long for regular crocheting
         HL_ofReg_C = "83. How long have you been crocheting regularly?",
         Feeling_when_KC = "84. What is your general experience when you knit/crochet? How do you feel?" ,
         Purpose_of_KC = "85. For what purpose do you knit/crochet?"  ,
         Med_Condtions = "86. Do you have a diagnosed condition? If so, would you mind telling us what?" ,
         #does the participant knit alone
         Knit_alone = "87. Do you knit/crochet...")

# Changing BDI scores to numeric 
df$BDI <- as.numeric(df$BDI)

# Change all relevant variables to factor variables
factor_cols <- c("Gender", "Knit_alone")
df[factor_cols] <- lapply(df[factor_cols], factor)

# create vector of continuous variables
cont_var <- c("BDI", "FMI", "PSS", "STAI")

# create vector of discrete variables
disc_var <- c("Freq_knit", "Session_L_Knit", "how_long_knit", "CrochetQ", "Session_L_Croch", "Knit_alone")

# Order pre/post factors for graphing
df$Freq_knit <- ordered(df$Freq_knit, levels = c("I do NOT knit.", "I knit once a month." , 
                                                "I knit once a week.", "I knit several times a week.",
                                                "I knit once a day.", "I knit several times a day." ))
df$Session_L_Knit <- ordered(df$Session_L_Knit, levels = c("Not applicable.", "15 minutes.", "30 minutes."  , "1 hour." , "2 hours." ,"3 hours or more."))
df$Session_L_Croch <- ordered(df$Session_L_Croch, levels = c("Not applicable.", "15 minutes.", "30 minutes."  , "1 hour." , "2 hours." ,"3 hours or more."))
df$how_long_knit <- ordered(df$how_long_knit, levels = c("Not applicable.", "6 months.", "Between 6 and 12 months."  , "About 2 years."     , "More than 3 years."  ))
df$CrochetQ <- ordered(df$CrochetQ, levels = c("I do NOT crochet." , "I crochet several times a day." , "I crochet once a day."  , "I crochet several times a week." , "I crochet once a week."  , 
                                               "I crochet once a month."))

# remove any rows containing NA in key variables
df <- df[complete.cases(df[disc_var], df[cont_var]), ]

#standardise continuous scale variables
df$BDI <- scale(df$BDI)
df$PSS <- scale(df$PSS)
df$STAI <- scale(df$STAI)
df$FMI <- scale(df$FMI)



```

## Data visualisation
```{r, eval = FALSE, include = FALSE}


# create mosaic plot to show overlap between knitters and crotcheters
ct <- xtabs(~Freq_knit + CrochetQ, df)
vcd::mosaic(ct, shade = TRUE, legend = TRUE,
            rot_labels = c(90, 0), varnames = FALSE, just_labels = "center",
            tl_labels = c(TRUE, FALSE))

#create boxplot function for both variables
box_fn = function(var1, var2) {
              ggplot(df, aes(x=.data[[var1]], y=.data[[var2]], fill=.data[[var1]])) + geom_boxplot() +  theme(legend.position = "bottom", legend.title = element_blank()) + easy_labs(y = df[,var2]) +
  stat_summary(fun = "mean", geom = "point", shape = 23, size = 3, fill = "red") +
    theme(axis.text.x = element_blank())}

#make boxplots
# lapply(disc_var,box_fn, var2 = "BDI")

for (i in 1:length(cont_var)) {
p <- lapply(disc_var,box_fn, var2 = cont_var[i])
print(p)
}

# Note that all well-being metrics are strongly correlated
c <- cor(select(df, BDI, FMI, STAI, PSS), use = "complete.obs")
corrplot::corrplot(c, diag = FALSE, type = "lower", method = "pie")

```

# Frequentist modelling
```{r, eval = FALSE, include=FALSE}

# remove factor ordering (otherwise lm function models polynomials)
df[disc_var] <- lapply(df[disc_var], factor, ordered = FALSE)

# fit linear models
# Key: L = linear model, M = mixed model, O = ordinal model
# dependent variable; B=BDI, P=PSS, S=STAI, F=FMI
# e.g. OB2 = ordinal model, BDI as DV, 2nd model in series

# BDI
model_LB1 <- lm(BDI ~ 1 + Freq_knit, data=df)
summary(model_LB1)
plot_model(model_LB1)

model_LB2 <- lm(BDI ~ 1 + Freq_knit + Session_L_Knit, data = df)
summary(model_LB2)
plot_model(model_LB2)

model_LB3 <- lm(BDI ~ 1 + Freq_knit + Session_L_Knit + how_long_knit, data = df)
summary(model_LB3)
plot_model(model_LB3)

tab_model(model_LB1, model_LB2, model_LB3, file = "models_BDI.html")

# PSS
model_LP1 <- lm(PSS ~ 1 + Freq_knit, data=df)
summary(model_LP1)
plot_model(model_LP1)

model_LP2 <- lm(PSS ~ 1 + Freq_knit + Session_L_Knit, data = df)
summary(model_LP2)
plot_model(model_LP2)

model_LP3 <- lm(PSS ~ 1 + Freq_knit + Session_L_Knit + how_long_knit, data = df)
summary(model_LP3)
plot_model(model_LP3)

tab_model(model_LP1, model_LP2, model_LP3)

#FMI
model_LF1 <- lm(FMI ~ 1 + Freq_knit, data=df)
summary(model_LF1)
plot_model(model_LF1)

model_LF2 <- lm(FMI ~ 1 + Freq_knit + Session_L_Knit, data = df)
summary(model_LF2)
plot_model(model_LF2)

model_LF3 <- lm(FMI ~ 1 + Freq_knit + Session_L_Knit + how_long_knit, data = df)
summary(model_LF3)
plot_model(model_LF3)

tab_model(model_LF1, model_LF2, model_LF3)

#STAI
model_LS1 <- lm(STAI ~ 1 + Freq_knit, data=df)
summary(model_LS1)
plot_model(model_LS1)

model_LS2 <- lm(STAI ~ 1 + Freq_knit + Session_L_Knit, data = df)
summary(model_LS2)
plot_model(model_LS2)

model_LS3 <- lm(STAI ~ 1 + Freq_knit + Session_L_Knit + how_long_knit, data = df)
summary(model_LS3)
plot_model(model_LS3)

tab_model(model_LS1, model_LS2, model_LS3)

# Multi-variate DV model
model_MA1 <- lm(cbind(BDI, FMI, STAI, PSS) ~ 1 + Freq_knit, data = df)
summary(model_MA1)
model_MA2 <- lm(cbind(BDI, FMI, STAI, PSS) ~ 1 + Freq_knit + Session_L_Knit, data = df)
summary(model_MA2)

tab_model(model_LB3, model_LF3, model_LS3, model_LP3)


```

# Frequentist modelling - knitters only
```{r, EVAL = FALSE, include=FALSE}

# remove factor ordering (otherwise lm function models polynomials)
df[disc_var] <- lapply(df[disc_var], factor, ordered = FALSE)

# fit linear models
# Key: L = linear model, M = mixed model, O = ordinal model
# dependent variable; B=BDI, P=PSS, S=STAI, F=FMI
# e.g. OB2 = ordinal model, BDI as DV, 2nd model in series

# BDI
model_LB1 <- lm(BDI ~ 1 + Freq_knit, data=(df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LB1)
plot_model(model_LB1)

model_LB2 <- lm(BDI ~ 1 + Freq_knit + Session_L_Knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LB2)
plot_model(model_LB2)

model_LB3 <- lm(BDI ~ 1 + Freq_knit + Session_L_Knit + how_long_knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LB3)
plot_model(model_LB3)

tab_model(model_LB1, model_LB2, model_LB3, file = "models_BDI.html")

# PSS
model_LP1 <- lm(PSS ~ 1 + Freq_knit, data=(df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LP1)
plot_model(model_LP1)

model_LP2 <- lm(PSS ~ 1 + Freq_knit + Session_L_Knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LP2)
plot_model(model_LP2)

model_LP3 <- lm(PSS ~ 1 + Freq_knit + Session_L_Knit + how_long_knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LP3)
plot_model(model_LP3)

tab_model(model_LP1, model_LP2, model_LP3)

#FMI
model_LF1 <- lm(FMI ~ 1 + Freq_knit, data=(df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LF1)
plot_model(model_LF1)

model_LF2 <- lm(FMI ~ 1 + Freq_knit + Session_L_Knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LF2)
plot_model(model_LF2)

model_LF3 <- lm(FMI ~ 1 + Freq_knit + Session_L_Knit + how_long_knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LF3)
plot_model(model_LF3)

tab_model(model_LF1, model_LF2, model_LF3)

#STAI
model_LS1 <- lm(STAI ~ 1 + Freq_knit, data=(df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LS1)
plot_model(model_LS1)

model_LS2 <- lm(STAI ~ 1 + Freq_knit + Session_L_Knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LS2)
plot_model(model_LS2)

model_LS3 <- lm(STAI ~ 1 + Freq_knit + Session_L_Knit + how_long_knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_LS3)
plot_model(model_LS3)

tab_model(model_LS1, model_LS2, model_LS3)

# Multi-variate DV model
model_MA1 <- lm(cbind(BDI, FMI, STAI, PSS) ~ 1 + Freq_knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_MA1)
model_MA2 <- lm(cbind(BDI, FMI, STAI, PSS) ~ 1 + Freq_knit + Session_L_Knit, data = (df %>% filter(Freq_knit != "I do NOT knit." & CrochetQ == "I do NOT crochet.")))
summary(model_MA2)

tab_model(model_LB3, model_LF3, model_LS3, model_LP3)

```

# Frequentist modelling - crotcheters only
```{r, eval=FALSE, include=FALSE}

# remove factor ordering (otherwise lm function models polynomials)
df[disc_var] <- lapply(df[disc_var], factor, ordered = FALSE)

# fit linear models
# Key: L = linear model, M = mixed model, O = ordinal model
# dependent variable; B=BDI, P=PSS, S=STAI, F=FMI
# e.g. OB2 = ordinal model, BDI as DV, 2nd model in series

# BDI
model_LB1 <- lm(BDI ~ 1 + CrochetQ, data=(df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_LB1)
plot_model(model_LB1)

model_LB2 <- lm(BDI ~ 1 + CrochetQ + Session_L_Croch, data = (df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_LB2)
plot_model(model_LB2)

tab_model(model_LB1, model_LB2)

# PSS
model_LP1 <- lm(PSS ~ 1 + CrochetQ, data=(df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_LP1)
plot_model(model_LP1)

model_LP2 <- lm(PSS ~ 1 + CrochetQ + Session_L_Croch, data = (df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_LP2)
plot_model(model_LP2)

tab_model(model_LP1, model_LP2)

#FMI
model_LF1 <- lm(FMI ~ 1 + CrochetQ, data=(df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_LF1)
plot_model(model_LF1)

model_LF2 <- lm(FMI ~ 1 + CrochetQ + Session_L_Croch, data = (df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_LF2)
plot_model(model_LF2)

tab_model(model_LF1, model_LF2)

#STAI
model_LS1 <- lm(STAI ~ 1 + CrochetQ, data=(df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_LS1)
plot_model(model_LS1)

model_LS2 <- lm(STAI ~ 1 + CrochetQ + Session_L_Croch, data = (df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_LS2)
plot_model(model_LS2)

tab_model(model_LS1, model_LS2)

# Multi-variate DV model
model_MA1 <- lm(cbind(BDI, FMI, STAI, PSS) ~ 1 + CrochetQ, data = (df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_MA1)
model_MA2 <- lm(cbind(BDI, FMI, STAI, PSS) ~ 1 + CrochetQ + Session_L_Croch, data = (df %>% filter(CrochetQ != "I do NOT crochet.")))
summary(model_MA2)

tab_model(model_LB3, model_LF3, model_LS3, model_LP3)

```

# Canonical correlation analysis
```{r, eval=FALSE, include=FALSE}
# select discrete variables to be analysed and convert factors to numeric
dmat <- lapply(df[c("Freq_knit", "Session_L_Knit", "how_long_knit")], as.numeric)

# run CCA
# convert variables into matrices
dmat <- matrix(unlist(dmat), ncol = 3)
dimnames(dmat)[[2]] = c("Freq", "SessionL", "Time")
cmat <- as.matrix(df[cont_var])

# matrix of correlations
matcor(cmat, dmat) %>% kbl(digits = 2) 

# run canonical correlation analysis
cca1 <- cc(dmat, cmat)
cca1$cor %>% kbl(digits = 3) %>% htmlTable::htmlTable()
 
cca1$xcoef %>% kbl(digits = 2) %>% htmlTable::htmlTable()
cca1$ycoef %>% kbl(digits = 2) %>% htmlTable::htmlTable()

# calculate canonical loadings (correlations between variables and latent canonical factors)
cc2 <- comput(dmat, cmat, cca1)
cc2$corr.X.xscores %>% kbl(digits = 2) %>% htmlTable::htmlTable()
cc2$corr.X.yscores %>% kbl(digits = 2) %>% htmlTable::htmlTable()
cc2$corr.Y.yscores %>% kbl(digits = 2) %>% htmlTable::htmlTable()
cc2$corr.Y.xscores %>% kbl(digits = 2) %>% htmlTable::htmlTable()

rbind(cc2$corr.X.xscores, cc2$corr.X.yscores, cc2$corr.Y.yscores, cc2$corr.Y.xscores ) %>% kbl(digits = 2) %>% htmlTable::htmlTable()

# tests of canonical dimensions
rho <- cca1$cor
## Define number of observations, number of variables in first set, and number of variables in the second set.
n <- dim(cmat)[1]
p <- ncol(cmat)
q <- ncol(dmat)

## Calculate p-values using the F-approximations of different test statistics:
CCP::p.asym(rho, n, p, q, tstat = "Wilks") %>% kbl(digits = 3) 

# standardized well-being canonical coefficients diagonal matrix of well-being sd's
s1 <- diag(sqrt(diag(cov(cmat))))
s1 %*% cca1$ycoef %>% kbl(digits = 2)

# standardized knitting canonical coefficients diagonal matrix of knitting sd's
s2 <- diag(sqrt(diag(cov(dmat))))
cca1$xcoef %*% s2 %>% kbl(digits = 2)

```

# Ordinal modelling
```{r, eval=FALSE, include=FALSE}

# note: need to restore factor levels
# Order pre/post factors 
df$Freq_knit <- ordered(df$Freq_knit, levels = c("I do NOT knit.", "I knit once a month." , 
                                                "I knit once a week.", "I knit several times a week.",
                                                "I knit once a day.", "I knit several times a day." ))
df$Session_L_Knit <- ordered(df$Session_L_Knit, levels = c("Not applicable.", "15 minutes.", "30 minutes."  , "1 hour." , "2 hours." ,"3 hours or more."))
df$Session_L_Croch <- ordered(df$Session_L_Croch, levels = c("Not applicable.", "15 minutes.", "30 minutes."  , "1 hour." , "2 hours." ,"3 hours or more."))
df$how_long_knit <- ordered(df$how_long_knit, levels = c("Not applicable.", "6 months.", "Between 6 and 12 months."  , "About 2 years."     , "More than 3 years."  ))
df$CrochetQ <- ordered(df$CrochetQ, levels = c("I do NOT crochet." , "I crochet several times a day." , "I crochet once a day."  , "I crochet several times a week." , "I crochet once a week."  , 
                                               "I crochet once a month."))



# ordinal predictor model
lambda <- c(1000,500,200,100,50,30,20,10,1,0)
model_OP1 <- ordSmooth(x = as.numeric(df$Freq_knit), y = df$BDI, lambda = lambda)
model_OP1$coefficients

model_OP2 <- ordSmooth(x = as.numeric(df$Freq_knit) + as.numeric(df$Session_L_Knit), y = df$BDI, lambda = lambda)
model_OP2$coefficients



# ordinal dependent variable models

# Model 1: Knitting Frequency
model_OD1 <- polr(Freq_knit ~ BDI + FMI + STAI + PSS, data = df, Hess=TRUE)
summary(model_OD1)

## calculate and store p values
ctable <- coef(summary(model_OD1))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
## combined table
(ctable <- cbind(ctable, "p value" = p))

## odds ratios and confidence intervals
ci <- confint.default(model_OD1)
exp(cbind("Odds ratio" = coef(model_OD1), ci))


# Model 2: Session Length
model_OD2 <- polr(Session_L_Knit ~ BDI + FMI + STAI + PSS, data = df, Hess=TRUE)
summary(model_OD2)

## calculate and store p values
ctable <- coef(summary(model_OD2))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
## combined table
(ctable <- cbind(ctable, "p value" = p))

## odds ratios and confidence intervals
ci <- confint.default(model_OD2)
exp(cbind("Odds ratio" = coef(model_OD2), ci))

# Model 3: Length of time knitting
model_OD3 <- polr(how_long_knit ~ BDI + FMI + STAI + PSS, data = df, Hess=TRUE)
summary(model_OD3)

## calculate and store p values
ctable <- coef(summary(model_OD3))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
## combined table
(ctable <- cbind(ctable, "p value" = p))

## odds ratios and confidence intervals
ci <- confint.default(model_OD3)
exp(cbind("Odds ratio" = coef(model_OD3), ci))

```


# Bayesian Modelling: knitters only
```{r, eval=FALSE, include=FALSE}

# remove factor ordering (otherwise lm function models polynomials)
df[disc_var] <- lapply(df[disc_var], factor, ordered = FALSE)







# Predict well-being from knitting variables



#Model 1k: Multi-variate knitting predictors of depression - DEFAULT (flat) priors
m1 <- brm(formula = BDI ~ Freq_knit + Session_L_Knit + how_long_knit, data = df, file = "m1.rds")

summary(m1)

prior_summary(m1)


#Model 1k: Multi-variate knitting predictors of depression - NORMAL priors
m1k <- brm(formula = BDI ~ Freq_knit + Session_L_Knit + how_long_knit, data = df, file = "m1knit.rds", sample_prior = TRUE, prior = set_prior("normal(0,2)", class = "b"))

summary(m1k)

prior_summary(m1k)

tab_model(m1, m1k, file = "comparison.html")


#Model 2: Multi-variate knitting predictors of mindfulness
m2 <- brm(formula = FMI ~ Freq_knit + Session_L_Knit + how_long_knit, data = df, file = "m2.rds")
summary(m2)
tab_model(m2, file = "m2.html")

#Model 3: Multi-variate knitting predictors of anxiety
m3 <- brm(formula = STAI ~ Freq_knit + Session_L_Knit + how_long_knit, data = df, file = "m3.rds")
summary(m3)
tab_model(m3, file = "m3.html")

#Model 4: Multi-variate knitting predictors of stress
m4 <- brm(formula = PSS ~ Freq_knit + Session_L_Knit + how_long_knit, data = df, file = "m4.rds")
summary(m4)
tab_model(m4, file = "m4.html")

          
```